# Generated by Django 3.2.7 on 2021-09-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.TextField()),
                ('username', models.CharField(max_length=32)),
                ('date_of_submission', models.DateField(auto_now=True)),
            ],
        ),
    ]
