# Generated by Django 3.2.7 on 2021-09-25 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managementsystem', '0002_blogs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('profile', models.CharField(blank=True, max_length=32)),
                ('branch', models.CharField(blank=True, max_length=32)),
                ('contact_info', models.CharField(blank=True, max_length=32)),
                ('reg_no', models.CharField(blank=True, max_length=10)),
                ('email_id', models.EmailField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('current_sem', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
