# Generated by Django 3.2.7 on 2021-09-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementsystem', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ENTC', 'ENTC'), ('MECH', 'MECH')], max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Student', 'student')], max_length=32),
        ),
    ]
